### ISSUE TITLE
orchidServe stuck at 85% Executing

### ISSUE THREAD

**Issue by ersin-ertan** [JavaEden/OrchidStarter#2]
Hey there, I'm trying the quick start, and after running `./gradlew orchidServe` the terminal process is stuck during the execution. See picture:
![orchid](https://user-images.githubusercontent.com/4809853/46905044-a3f8d500-cebb-11e8-8e62-135ba6759e8f.png)

**Also note** that navigating to the localhost will show the site, however because execution did not finish, I'm not sure it is all there(visually it look complete)

**Comment by cjbrooks12** [comment]
This is the intended behavior. `./gradlew orchidServe` builds the site and hosts it for your for development and testing, which means the process will continue waiting for requests until you exit the process to shut down the server. The results table and the `Build Complete` line in the screenshot tells you that the site _has_ been successfully built, and what you're seeing on localhost is the same site you'd see when deployed elsewhere, because the server is just sending back the files on disk.

To get the process to build once and then exit, use the `./gradlew orchidBuild` command.
